language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: hxrq6lF5h0JOfgJqRBsNlhjbgk2x9qzTimQj88du1jS1qoYUf5U3kIwXtB+4yvjPsh/G9rmoo7q0k/Nsq2b+6YOSelR6xr8fQw6R7V/iO0d06QyFTqrnQvK8Wcd220YQi0c6vYtBQdodU7h/QWENOMU4pleqycUuc8McFVzldvK26P+tUkEATGFl28tyl39Am+ovWkIz+jZ2OTgY79ZEf429577KWBXWuoBM6LrXApfS3rQepkrcHBSKdSfHyeFZchtUcvthG7Po2kEK3Qqy6lCRJ2eBLfcVWNC79wOdQ+0x1ZM/ZzDcBoTe94GuUclmPcMHivGVoef5qQ8dPFGVpHyOxgsiuBHTwWHctbRsZO113GQM2aUi1zNWOU+hlWPk/sNzdZ100ulfNrxDSa3sWx9BqA/AQCva0H9KZdgJsfVAdekqJsYBgFuW9BjR5h//N0fsxajI70qFzrZpezQlpmSks+vv0COhiAtSM1gQVpWuM432BxmwTVv8Fns1YIum7LocBRKkg8ss8sxmtN5hjApXtgb4wLJiV54tWttmTjoqIM0WHmvKeMGH7XpXNntWSR0hlUjdPTnIbn8XP/ruf/qFz5kdyAmfcjfhMMd/qxnrh+MvvRuKBduI9FxEM520OjCbw8tvkMeOYMBm251lZVLCwUi10XEUlutB9vcLjzs=
